package com.jpa.tutorial.ggi.enums;

public enum InsuranceType {
    LIFE,
    MEDICAL,
    TRAVEL_INSURANCE,
    FIDELITY,
    PERSON_TRAVEL,
    PERSONAL_ACCIDENT,
    FARMER,
    SHORT_TERM_ENDOWMENT,
    HEALTH,
    MICRO_HEALTH,
    CRITICAL_ILLNESS,
    GROUP_MICRO_HEALTH,
    GROUP_FARMER,
    STUDENT_LIFE,
    PUBLIC_TERM_LIFE,
    SINGLE_PREMIUM_CREDIT_LIFE,
    SINGLE_PREMIUM_ENDOWMENT_LIFE,
    SHORT_TERM_SINGLE_PREMIUM_CREDIT_LIFE,
    SIMPLE_LIFE
}
